version: '3.7'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./config/nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - nginx.docker

networks:
  nginx.docker:
    name: nginx.docker
    external: true